# Customize to your needs...
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/Users/sonesuke/.pythonbrew/bin:/Users/sonesuke/.pythonbrew/pythons/Python-2.7.2/bin:/Users/sonesuke/Library/Haskell/bin:/Library/Frameworks/Python.framework/Versions/2.6/bin:/opt/local/sbin/:/Library/Frameworks/Python.framework/Versions/Current/bin:/Users/sonesuke/.rvm/bin:/Users/sonesuke/py33/bin
